parameters:
    guzzle_http.message_formatter.class: GuzzleHttp\MessageFormatter
    mapudo.guzzle.middleware.event_dispatch_middleware.class: Mapudo\Bundle\GuzzleBundle\Middleware\EventDispatchMiddleware
    mapudo.guzzle.middleware.log_middleware.class: Mapudo\Bundle\GuzzleBundle\Middleware\LogMiddleware

services:
    mapudo_bundle_guzzle.data_collector.request_data_collector:
        class: Mapudo\Bundle\GuzzleBundle\DataCollector\RequestDataCollector
        public: false
        tags:
            - { name: data_collector, template: '@Guzzle/debug.html.twig', id: guzzle }
    mapudo_bundle_guzzle.serializer:
        class: Symfony\Component\Serializer\Serializer
    mapudo_bundle_guzzle.serializer.name_converter.camel_case_to_snake_case:
        class: Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter
    mapudo_bundle_guzzle.serializer.normalizer.object:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        tags:
            - { name: mapudo_bundle_guzzle.serializer.normalizer, priority: 1 }
        arguments: ['@=null', '@mapudo_bundle_guzzle.serializer.name_converter.camel_case_to_snake_case']
    mapudo_bundle_guzzle.log_serializer_denormalizer.response_denormalizer:
        class: Mapudo\Bundle\GuzzleBundle\Log\Serializer\Denormalizer\ResponseDenormalizer
        tags:
            - { name: mapudo_bundle_guzzle.serializer.normalizer, priority: 2 }
    mapudo_bundle_guzzle.log_serializer_denormalizer.request_denormalizer:
        class: Mapudo\Bundle\GuzzleBundle\Log\Serializer\Denormalizer\RequestDenormalizer
        tags:
            - { name: mapudo_bundle_guzzle.serializer.normalizer, priority: 3 }
    mapudo_bundle_guzzle.log_handler.symfony_profiler_handler:
        class: Mapudo\Bundle\GuzzleBundle\Log\Handler\SymfonyProfilerHandler
        arguments: ['@mapudo_bundle_guzzle.data_collector.request_data_collector', '@mapudo_bundle_guzzle.serializer']
